### ISSUE TITLE
On/off switch not working

### ISSUE THREAD

**Issue by DavidMStraub** [DavidMStraub/homeassistant-homeconnect#10]
At least power off should be possible.

**Comment by areeeee** [comment]
on and off works with my siemens dishwasher from the app. can't find an on/off switch in HA though...?

**Comment by DavidMStraub** [comment]
There should be a switch entity with the name of your appliance. I just pushed a few changes to the code that fix a problem with this power switch. However for my dryer it still doesn't work. It would be interesting to know whether this now works for your dishwasher.

**Comment by MarcusKapun** [comment]
David - really like your initiative regarding homeconnect, thanks a lot. Also testing as have coffee machine, dishwasher and oven. All is discovered and binary sensors as well as sensors are working well (with the limitations stated in the issues). Regarding the switches, when triggering it's stated immediately back to 'off' and reports following error report in the log:

`Log Details (ERROR)

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncio/tasks.py", line 241, in _step
    result = coro.throw(exc)
  File "/srv/homeassistant/lib/python3.5/site-packages/homeassistant/helpers/service.py", line 287, in _handle_service_platform_call
    await getattr(entity, func)(**data)
  File "/usr/lib/python3.5/asyncio/futures.py", line 380, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/lib/python3.5/asyncio/tasks.py", line 304, in _wakeup
    future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 293, in result
    raise self._exception
  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/homeassistant/.homeassistant/custom_components/switch/homeconnect.py", line 89, in turn_on
    self.device.appliance.set_setting('BSH.Common.Setting.PowerState',  'BSH.Common.Setting.PowerState.On')
  File "/srv/homeassistant/lib/python3.5/site-packages/homeconnect/api.py", line 261, in set_setting
    return self.put('/settings/{}'.format(settingkey), {'data': {'key': settingkey, 'value': value}})
  File "/srv/homeassistant/lib/python3.5/site-packages/homeconnect/api.py", line 214, in put
    return self.hc.put('{}/{}{}'.format(ENDPOINT_APPLIANCES, self.haId, endpoint), data)
  File "/srv/homeassistant/lib/python3.5/site-packages/homeconnect/api.py", line 127, in put
    raise HomeConnectError(res['error'])
homeconnect.api.HomeConnectError: {'description': 'Key BSH.Common.Setting.PowerState has unknown enum type or enum member BSH.Common.Setting.PowerState.On.', 'key': 'SDK.Error.InvalidSettingValue'}`

Hope that helps. Let me know if you need more details.

Thanks again for your work on that project!
Marcus

**Comment by DavidMStraub** [comment]
Thanks, that is indeed helpful. I got back the same error from the API simulator but was not sure whether this was just a limitation of the simulator. I now sent a request to the API  developers, because according to their docs this is supposed to work.

**Comment by DavidMStraub** [comment]
Replies from the API devs:

> The reason behind it is a fact, that not all devices can be turned ON or OFF by using API. If you check following page: https://developer.home-connect.com/docs/settings/power_state you can see that dryer can be only turned ON using API. Basically you can turn OFF only dishwasher, cooktop or hood. That is why you couldn’t control your physical dryer.

> Regarding coffee machine – from which state did you tried to turn it on? In case of coffee machine it is possible to do so, when device is put to ‘Standby’ state. I had possibility to check it on our side, and device change its power state to ‘Standby’ and back without a problem.

What you could try is whether you can switch the coffee machine on or off by directly issuing commands using the Python package. You can use the `.homeconnect-token-cache` file from your Home Assistant directory and then, in a Python session, do:

```python
from homeconnect import Homeconnect
hc = HomeConnect(MY_CLIENT_ID, MY_CLIENT_SECRET, token_cache='.homeconnect-token-cache')
hc.get_appliances()
```
From the list of appliances, choose the appropriate one (let's call it `app`) and then do

```python
# one of:
app.set_setting("BSH.Common.Setting.PowerState", "BSH.Common.EnumType.PowerState.On")
app.set_setting("BSH.Common.Setting.PowerState", "BSH.Common.EnumType.PowerState.Off")
app.set_setting("BSH.Common.Setting.PowerState", "BSH.Common.EnumType.PowerState.Standby")
```

The supported values are [listed here](https://developer.home-connect.com/docs/settings/power_state). It would be very useful to know what you get for the various devices; what doesn't work like this will not work in HA either.

By the way, note that you might have to press the "remote start" button on some devices, not sure when/whether this is needed.

**Comment by MarcusKapun** [comment]
Thanks, David. Changed line 89 of the switch.py from

`self.device.appliance.set_setting('BSH.Common.Setting.PowerState',  'BSH.Common.Setting.PowerState.On')`

to

`self.device.appliance.set_setting('BSH.Common.Setting.PowerState',  'BSH.Common.EnumType.PowerState.On')`

and the on switch is working now for all devices I have (dishwasher, coffee machine and oven), but at the same time the following error message is shown:

> Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.5/site-packages/homeconnect/api.py", line 123, in put
    res = res.json()
  File "/srv/homeassistant/lib/python3.5/site-packages/requests/models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3.5/json/__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.5/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.5/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncio/tasks.py", line 241, in _step
    result = coro.throw(exc)
  File "/srv/homeassistant/lib/python3.5/site-packages/homeassistant/helpers/service.py", line 289, in _handle_service_platform_call
    await getattr(entity, func)(**data)
  File "/usr/lib/python3.5/asyncio/futures.py", line 380, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/lib/python3.5/asyncio/tasks.py", line 304, in _wakeup
    future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 293, in result
    raise self._exception
  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/homeassistant/.homeassistant/custom_components/homeconnect/switch.py", line 89, in turn_on
    self.device.appliance.set_setting('BSH.Common.Setting.PowerState',  'BSH.Common.EnumType.PowerState.On')
  File "/srv/homeassistant/lib/python3.5/site-packages/homeconnect/api.py", line 261, in set_setting
    return self.put('/settings/{}'.format(settingkey), {'data': {'key': settingkey, 'value': value}})
  File "/srv/homeassistant/lib/python3.5/site-packages/homeconnect/api.py", line 214, in put
    return self.hc.put('{}/{}{}'.format(ENDPOINT_APPLIANCES, self.haId, endpoint), data)
  File "/srv/homeassistant/lib/python3.5/site-packages/homeconnect/api.py", line 125, in put
    raise ValueError("Cannot parse {} as JSON".format(res))
ValueError: Cannot parse <Response [204]> as JSON

**Comment by DavidMStraub** [comment]
Oh, thanks so much! That was the problem all along! I pushed the change now.

Concerning the error, that is due to some missing error handling in the `homeconnect` Python package; I suspect this was already partly solved in v0.2 but I now added a bit more and released a version 0.2.1 to PyPI.

Please let me know if after `pip3 install --upgrade homeconnect` the switches now work for  you without errors.

Thanks again!

**Comment by areeeee** [comment]
I can now turn on my dishwasher in HA, but off does not work. The switch does not update if I turn the dishwasher on and off outside HA.

**Comment by MarcusKapun** [comment]
No, still triggers the same error message as posted previously. Also, the "off" / "standby" function is not working and I have the same issue as areeeee. Unfortunately, both actions do not trigger any error log in HA.

**Comment by areeeee** [comment]
On via HA works and the switch remains on (but does not change if the dishwasher turns off).

No update in HA if I turn on/off the dishwasher via the homeconnect app or physically.

Here are some logs if it helps:
# ON VIA HA
```
2019-02-27 20:39:21 DEBUG (Thread-4) [custom_components.homeconnect] Update triggered on Oppvaskmaskin
2019-02-27 20:39:21 DEBUG (Thread-4) [custom_components.homeconnect] [<Entity Oppvaskmaskin Door: off>, <Entity Oppvaskmaskin Remaining Program Time: None>, <Entity Oppvaskmaskin Program Progress: None>, <Entity Oppvaskmaskin Program Auto1: off>, <Entity Oppvaskmaskin Program Auto2: off>, <Entity Oppvaskmaskin Program Auto3: off>, <Entity Oppvaskmaskin Program Eco50: off>, <Entity Oppvaskmaskin Program Quick45: off>]
2019-02-27 20:39:21 DEBUG (Thread-4) [custom_components.homeconnect] {'BSH.Common.Status.DoorState': {'value': 'BSH.Common.EnumType.DoorState.Closed'}, 'BSH.Common.Status.OperationState': {'timestamp': 1551296361, 'handling': 'none', 'uri': '/api/homeappliances/SIEMENS-SN678X56TS-REMOVED/status/BSH.Common.Status.OperationState', 'value': 'BSH.Common.EnumType.OperationState.Ready', 'level': 'hint'}, 'BSH.Common.Status.RemoteControlActive': {'value': True}, 'BSH.Common.Status.RemoteControlStartAllowed': {'value': False}, 'BSH.Common.Setting.PowerState': {'timestamp': 1551295947, 'handling': 'none', 'uri': '/api/homeappliances/SIEMENS-SN678X56TS-REMOVED/settings/BSH.Common.Setting.PowerState', 'value': 'BSH.Common.EnumType.PowerState.Off', 'level': 'hint'}}
2019-02-27 20:39:21 DEBUG (Thread-4) [custom_components.homeconnect] Entity update triggered on <Entity Oppvaskmaskin Door: off>
2019-02-27 20:39:21 DEBUG (Thread-4) [custom_components.homeconnect] Entity update triggered on <Entity Oppvaskmaskin Remaining Program Time: None>
2019-02-27 20:39:21 DEBUG (Thread-4) [custom_components.homeconnect] Entity update triggered on <Entity Oppvaskmaskin Program Progress: None>
2019-02-27 20:39:21 DEBUG (SyncWorker_7) [custom_components.homeconnect.binary_sensor] Updated, new state: False
2019-02-27 20:39:21 DEBUG (SyncWorker_3) [custom_components.homeconnect.sensor] Updated, new state: None
2019-02-27 20:39:21 DEBUG (Thread-4) [custom_components.homeconnect] Entity update triggered on <Entity Oppvaskmaskin Program Auto1: off>
2019-02-27 20:39:21 DEBUG (SyncWorker_4) [custom_components.homeconnect.sensor] Updated, new state: None
2019-02-27 20:39:21 DEBUG (Thread-4) [custom_components.homeconnect] Entity update triggered on <Entity Oppvaskmaskin Program Auto2: off>
2019-02-27 20:39:21 DEBUG (SyncWorker_11) [custom_components.homeconnect.switch] Updated, new state: False
2019-02-27 20:39:21 DEBUG (Thread-4) [custom_components.homeconnect] Entity update triggered on <Entity Oppvaskmaskin Program Auto3: off>
2019-02-27 20:39:21 DEBUG (Thread-4) [custom_components.homeconnect] Entity update triggered on <Entity Oppvaskmaskin Program Eco50: off>
2019-02-27 20:39:21 DEBUG (SyncWorker_19) [custom_components.homeconnect.switch] Updated, new state: False
2019-02-27 20:39:21 DEBUG (Thread-4) [custom_components.homeconnect] Entity update triggered on <Entity Oppvaskmaskin Program Quick45: off>
2019-02-27 20:39:21 DEBUG (Thread-4) [custom_components.homeconnect] Update triggered on Oppvaskmaskin
2019-02-27 20:39:21 DEBUG (Thread-4) [custom_components.homeconnect] [<Entity Oppvaskmaskin Door: off>, <Entity Oppvaskmaskin Remaining Program Time: None>, <Entity Oppvaskmaskin Program Progress: None>, <Entity Oppvaskmaskin Program Auto1: off>, <Entity Oppvaskmaskin Program Auto2: off>, <Entity Oppvaskmaskin Program Auto3: off>, <Entity Oppvaskmaskin Program Eco50: off>, <Entity Oppvaskmaskin Program Quick45: off>]
2019-02-27 20:39:21 DEBUG (SyncWorker_15) [custom_components.homeconnect.switch] Updated, new state: False
2019-02-27 20:39:21 DEBUG (Thread-4) [custom_components.homeconnect] {'BSH.Common.Status.DoorState': {'value': 'BSH.Common.EnumType.DoorState.Closed'}, 'BSH.Common.Status.OperationState': {'timestamp': 1551296361, 'handling': 'none', 'uri': '/api/homeappliances/SIEMENS-SN678X56TS-REMOVED/status/BSH.Common.Status.OperationState', 'value': 'BSH.Common.EnumType.OperationState.Ready', 'level': 'hint'}, 'BSH.Common.Status.RemoteControlActive': {'value': True}, 'BSH.Common.Status.RemoteControlStartAllowed': {'value': False}, 'BSH.Common.Setting.PowerState': {'timestamp': 1551296361, 'handling': 'none', 'uri': '/api/homeappliances/SIEMENS-SN678X56TS-REMOVED/settings/BSH.Common.Setting.PowerState', 'value': 'BSH.Common.EnumType.PowerState.On', 'level': 'hint'}}
2019-02-27 20:39:21 DEBUG (Thread-4) [custom_components.homeconnect] Entity update triggered on <Entity Oppvaskmaskin Door: off>
2019-02-27 20:39:21 DEBUG (SyncWorker_6) [custom_components.homeconnect.switch] Updated, new state: False
2019-02-27 20:39:21 DEBUG (Thread-4) [custom_components.homeconnect] Entity update triggered on <Entity Oppvaskmaskin Remaining Program Time: None>
2019-02-27 20:39:21 DEBUG (SyncWorker_6) [custom_components.homeconnect.binary_sensor] Updated, new state: False
2019-02-27 20:39:21 DEBUG (Thread-4) [custom_components.homeconnect] Entity update triggered on <Entity Oppvaskmaskin Program Progress: None>
2019-02-27 20:39:21 DEBUG (SyncWorker_17) [custom_components.homeconnect.switch] Updated, new state: False
2019-02-27 20:39:21 DEBUG (SyncWorker_9) [custom_components.homeconnect.sensor] Updated, new state: None
2019-02-27 20:39:21 DEBUG (Thread-4) [custom_components.homeconnect] Entity update triggered on <Entity Oppvaskmaskin Program Auto1: off>
2019-02-27 20:39:21 DEBUG (SyncWorker_16) [custom_components.homeconnect.sensor] Updated, new state: None
2019-02-27 20:39:21 DEBUG (Thread-4) [custom_components.homeconnect] Entity update triggered on <Entity Oppvaskmaskin Program Auto2: off>
2019-02-27 20:39:21 DEBUG (SyncWorker_10) [custom_components.homeconnect.switch] Updated, new state: False
2019-02-27 20:39:21 DEBUG (Thread-4) [custom_components.homeconnect] Entity update triggered on <Entity Oppvaskmaskin Program Auto3: off>
2019-02-27 20:39:21 DEBUG (SyncWorker_3) [custom_components.homeconnect.switch] Updated, new state: False
2019-02-27 20:39:21 DEBUG (Thread-4) [custom_components.homeconnect] Entity update triggered on <Entity Oppvaskmaskin Program Eco50: off>
2019-02-27 20:39:21 DEBUG (SyncWorker_4) [custom_components.homeconnect.switch] Updated, new state: False
2019-02-27 20:39:21 DEBUG (Thread-4) [custom_components.homeconnect] Entity update triggered on <Entity Oppvaskmaskin Program Quick45: off>
2019-02-27 20:39:21 DEBUG (SyncWorker_8) [custom_components.homeconnect.switch] Updated, new state: False
2019-02-27 20:39:21 DEBUG (SyncWorker_1) [custom_components.homeconnect.switch] Updated, new state: False
```

# OFF VIA HA
Nothing

# ON VIA APP
```
2019-02-27 20:45:18 DEBUG (Thread-4) [custom_components.homeconnect] Update triggered on Oppvaskmaskin
2019-02-27 20:45:18 DEBUG (Thread-4) [custom_components.homeconnect] [<Entity Oppvaskmaskin Door: off>, <Entity Oppvaskmaskin Remaining Program Time: None>, <Entity Oppvaskmaskin Program Progress: None>, <Entity Oppvaskmaskin Program Auto1: off>, <Entity Oppvaskmaskin Program Auto2: off>, <Entity Oppvaskmaskin Program Auto3: off>, <Entity Oppvaskmaskin Program Eco50: off>, <Entity Oppvaskmaskin Program Quick45: off>]
2019-02-27 20:45:18 DEBUG (Thread-4) [custom_components.homeconnect] {'BSH.Common.Status.DoorState': {'value': 'BSH.Common.EnumType.DoorState.Closed'}, 'BSH.Common.Status.OperationState': {'timestamp': 1551296718, 'handling': 'none', 'uri': '/api/homeappliances/SIEMENS-SN678X56TS-REMOVED/status/BSH.Common.Status.OperationState', 'value': 'BSH.Common.EnumType.OperationState.Ready', 'level': 'hint'}, 'BSH.Common.Status.RemoteControlActive': {'value': True}, 'BSH.Common.Status.RemoteControlStartAllowed': {'value': False}, 'BSH.Common.Setting.PowerState': {'timestamp': 1551296583, 'handling': 'none', 'uri': '/api/homeappliances/SIEMENS-SN678X56TS-REMOVED/settings/BSH.Common.Setting.PowerState', 'value': 'BSH.Common.EnumType.PowerState.Off', 'level': 'hint'}}
2019-02-27 20:45:18 DEBUG (Thread-4) [custom_components.homeconnect] Entity update triggered on <Entity Oppvaskmaskin Door: off>
2019-02-27 20:45:18 DEBUG (Thread-4) [custom_components.homeconnect] Entity update triggered on <Entity Oppvaskmaskin Remaining Program Time: None>
2019-02-27 20:45:18 DEBUG (Thread-4) [custom_components.homeconnect] Entity update triggered on <Entity Oppvaskmaskin Program Progress: None>
2019-02-27 20:45:18 DEBUG (SyncWorker_18) [custom_components.homeconnect.binary_sensor] Updated, new state: False
2019-02-27 20:45:18 DEBUG (Thread-4) [custom_components.homeconnect] Entity update triggered on <Entity Oppvaskmaskin Program Auto1: off>
2019-02-27 20:45:18 DEBUG (SyncWorker_2) [custom_components.homeconnect.sensor] Updated, new state: None
2019-02-27 20:45:18 DEBUG (Thread-4) [custom_components.homeconnect] Entity update triggered on <Entity Oppvaskmaskin Program Auto2: off>
2019-02-27 20:45:18 DEBUG (SyncWorker_4) [custom_components.homeconnect.switch] Updated, new state: False
2019-02-27 20:45:18 DEBUG (SyncWorker_9) [custom_components.homeconnect.sensor] Updated, new state: None
2019-02-27 20:45:18 DEBUG (Thread-4) [custom_components.homeconnect] Entity update triggered on <Entity Oppvaskmaskin Program Auto3: off>
2019-02-27 20:45:18 DEBUG (SyncWorker_1) [custom_components.homeconnect.switch] Updated, new state: False
2019-02-27 20:45:18 DEBUG (Thread-4) [custom_components.homeconnect] Entity update triggered on <Entity Oppvaskmaskin Program Eco50: off>
2019-02-27 20:45:18 DEBUG (SyncWorker_3) [custom_components.homeconnect.switch] Updated, new state: False
2019-02-27 20:45:18 DEBUG (Thread-4) [custom_components.homeconnect] Entity update triggered on <Entity Oppvaskmaskin Program Quick45: off>
2019-02-27 20:45:18 DEBUG (SyncWorker_5) [custom_components.homeconnect.switch] Updated, new state: False
2019-02-27 20:45:18 DEBUG (Thread-4) [custom_components.homeconnect] Update triggered on Oppvaskmaskin
2019-02-27 20:45:18 DEBUG (Thread-4) [custom_components.homeconnect] [<Entity Oppvaskmaskin Door: off>, <Entity Oppvaskmaskin Remaining Program Time: None>, <Entity Oppvaskmaskin Program Progress: None>, <Entity Oppvaskmaskin Program Auto1: off>, <Entity Oppvaskmaskin Program Auto2: off>, <Entity Oppvaskmaskin Program Auto3: off>, <Entity Oppvaskmaskin Program Eco50: off>, <Entity Oppvaskmaskin Program Quick45: off>]
2019-02-27 20:45:18 DEBUG (SyncWorker_15) [custom_components.homeconnect.switch] Updated, new state: False
2019-02-27 20:45:18 DEBUG (Thread-4) [custom_components.homeconnect] {'BSH.Common.Status.DoorState': {'value': 'BSH.Common.EnumType.DoorState.Closed'}, 'BSH.Common.Status.OperationState': {'timestamp': 1551296718, 'handling': 'none', 'uri': '/api/homeappliances/SIEMENS-SN678X56TS-REMOVED/status/BSH.Common.Status.OperationState', 'value': 'BSH.Common.EnumType.OperationState.Ready', 'level': 'hint'}, 'BSH.Common.Status.RemoteControlActive': {'value': True}, 'BSH.Common.Status.RemoteControlStartAllowed': {'value': False}, 'BSH.Common.Setting.PowerState': {'timestamp': 1551296718, 'handling': 'none', 'uri': '/api/homeappliances/SIEMENS-SN678X56TS-REMOVED/settings/BSH.Common.Setting.PowerState', 'value': 'BSH.Common.EnumType.PowerState.On', 'level': 'hint'}}
2019-02-27 20:45:18 DEBUG (Thread-4) [custom_components.homeconnect] Entity update triggered on <Entity Oppvaskmaskin Door: off>
2019-02-27 20:45:18 DEBUG (Thread-4) [custom_components.homeconnect] Entity update triggered on <Entity Oppvaskmaskin Remaining Program Time: None>
2019-02-27 20:45:18 DEBUG (SyncWorker_10) [custom_components.homeconnect.binary_sensor] Updated, new state: False
2019-02-27 20:45:18 DEBUG (Thread-4) [custom_components.homeconnect] Entity update triggered on <Entity Oppvaskmaskin Program Progress: None>
2019-02-27 20:45:18 DEBUG (SyncWorker_10) [custom_components.homeconnect.sensor] Updated, new state: None
2019-02-27 20:45:18 DEBUG (Thread-4) [custom_components.homeconnect] Entity update triggered on <Entity Oppvaskmaskin Program Auto1: off>
2019-02-27 20:45:18 DEBUG (SyncWorker_6) [custom_components.homeconnect.sensor] Updated, new state: None
2019-02-27 20:45:18 DEBUG (Thread-4) [custom_components.homeconnect] Entity update triggered on <Entity Oppvaskmaskin Program Auto2: off>
2019-02-27 20:45:18 DEBUG (SyncWorker_18) [custom_components.homeconnect.switch] Updated, new state: False
2019-02-27 20:45:18 DEBUG (Thread-4) [custom_components.homeconnect] Entity update triggered on <Entity Oppvaskmaskin Program Auto3: off>
2019-02-27 20:45:18 DEBUG (SyncWorker_2) [custom_components.homeconnect.switch] Updated, new state: False
2019-02-27 20:45:18 DEBUG (Thread-4) [custom_components.homeconnect] Entity update triggered on <Entity Oppvaskmaskin Program Eco50: off>
2019-02-27 20:45:18 DEBUG (SyncWorker_4) [custom_components.homeconnect.switch] Updated, new state: False
2019-02-27 20:45:18 DEBUG (Thread-4) [custom_components.homeconnect] Entity update triggered on <Entity Oppvaskmaskin Program Quick45: off>
2019-02-27 20:45:18 DEBUG (SyncWorker_9) [custom_components.homeconnect.switch] Updated, new state: False
2019-02-27 20:45:18 DEBUG (SyncWorker_7) [custom_components.homeconnect.switch] Updated, new state: False
```

# OFF VIA APP
```
2019-02-27 20:47:57 DEBUG (Thread-4) [custom_components.homeconnect] Update triggered on Oppvaskmaskin
2019-02-27 20:47:57 DEBUG (Thread-4) [custom_components.homeconnect] [<Entity Oppvaskmaskin Door: off>, <Entity Oppvaskmaskin Remaining Program Time: None>, <Entity Oppvaskmaskin Program Progress: None>, <Entity Oppvaskmaskin Program Auto1: off>, <Entity Oppvaskmaskin Program Auto2: off>, <Entity Oppvaskmaskin Program Auto3: off>, <Entity Oppvaskmaskin Program Eco50: off>, <Entity Oppvaskmaskin Program Quick45: off>]
2019-02-27 20:47:57 DEBUG (Thread-4) [custom_components.homeconnect] {'BSH.Common.Status.DoorState': {'value': 'BSH.Common.EnumType.DoorState.Closed'}, 'BSH.Common.Status.OperationState': {'timestamp': 1551296877, 'handling': 'none', 'uri': '/api/homeappliances/SIEMENS-SN678X56TS-REMOVED/status/BSH.Common.Status.OperationState', 'value': 'BSH.Common.EnumType.OperationState.Inactive', 'level': 'hint'}, 'BSH.Common.Status.RemoteControlActive': {'value': True}, 'BSH.Common.Status.RemoteControlStartAllowed': {'value': False}, 'BSH.Common.Setting.PowerState': {'timestamp': 1551296718, 'handling': 'none', 'uri': '/api/homeappliances/SIEMENS-SN678X56TS-REMOVED/settings/BSH.Common.Setting.PowerState', 'value': 'BSH.Common.EnumType.PowerState.On', 'level': 'hint'}}
2019-02-27 20:47:57 DEBUG (Thread-4) [custom_components.homeconnect] Entity update triggered on <Entity Oppvaskmaskin Door: off>
2019-02-27 20:47:57 DEBUG (Thread-4) [custom_components.homeconnect] Entity update triggered on <Entity Oppvaskmaskin Remaining Program Time: None>
2019-02-27 20:47:57 DEBUG (Thread-4) [custom_components.homeconnect] Entity update triggered on <Entity Oppvaskmaskin Program Progress: None>
2019-02-27 20:47:57 DEBUG (SyncWorker_6) [custom_components.homeconnect.binary_sensor] Updated, new state: False
2019-02-27 20:47:57 DEBUG (SyncWorker_13) [custom_components.homeconnect.sensor] Updated, new state: None
2019-02-27 20:47:57 DEBUG (Thread-4) [custom_components.homeconnect] Entity update triggered on <Entity Oppvaskmaskin Program Auto1: off>
2019-02-27 20:47:57 DEBUG (Thread-4) [custom_components.homeconnect] Entity update triggered on <Entity Oppvaskmaskin Program Auto2: off>
2019-02-27 20:47:57 DEBUG (Thread-4) [custom_components.homeconnect] Entity update triggered on <Entity Oppvaskmaskin Program Auto3: off>
2019-02-27 20:47:57 DEBUG (SyncWorker_2) [custom_components.homeconnect.sensor] Updated, new state: None
2019-02-27 20:47:57 DEBUG (SyncWorker_5) [custom_components.homeconnect.switch] Updated, new state: False
2019-02-27 20:47:57 DEBUG (Thread-4) [custom_components.homeconnect] Entity update triggered on <Entity Oppvaskmaskin Program Eco50: off>
2019-02-27 20:47:57 DEBUG (SyncWorker_18) [custom_components.homeconnect.switch] Updated, new state: False
2019-02-27 20:47:57 DEBUG (Thread-4) [custom_components.homeconnect] Entity update triggered on <Entity Oppvaskmaskin Program Quick45: off>
2019-02-27 20:47:57 DEBUG (Thread-4) [custom_components.homeconnect] Update triggered on Oppvaskmaskin
2019-02-27 20:47:57 DEBUG (SyncWorker_7) [custom_components.homeconnect.switch] Updated, new state: False
2019-02-27 20:47:57 DEBUG (Thread-4) [custom_components.homeconnect] [<Entity Oppvaskmaskin Door: off>, <Entity Oppvaskmaskin Remaining Program Time: None>, <Entity Oppvaskmaskin Program Progress: None>, <Entity Oppvaskmaskin Program Auto1: off>, <Entity Oppvaskmaskin Program Auto2: off>, <Entity Oppvaskmaskin Program Auto3: off>, <Entity Oppvaskmaskin Program Eco50: off>, <Entity Oppvaskmaskin Program Quick45: off>]
2019-02-27 20:47:57 DEBUG (SyncWorker_16) [custom_components.homeconnect.switch] Updated, new state: False
2019-02-27 20:47:57 DEBUG (Thread-4) [custom_components.homeconnect] {'BSH.Common.Status.DoorState': {'value': 'BSH.Common.EnumType.DoorState.Closed'}, 'BSH.Common.Status.OperationState': {'timestamp': 1551296877, 'handling': 'none', 'uri': '/api/homeappliances/SIEMENS-SN678X56TS-REMOVED/status/BSH.Common.Status.OperationState', 'value': 'BSH.Common.EnumType.OperationState.Inactive', 'level': 'hint'}, 'BSH.Common.Status.RemoteControlActive': {'value': True}, 'BSH.Common.Status.RemoteControlStartAllowed': {'value': False}, 'BSH.Common.Setting.PowerState': {'timestamp': 1551296877, 'handling': 'none', 'uri': '/api/homeappliances/SIEMENS-SN678X56TS-REMOVED/settings/BSH.Common.Setting.PowerState', 'value': 'BSH.Common.EnumType.PowerState.Off', 'level': 'hint'}}
2019-02-27 20:47:57 DEBUG (Thread-4) [custom_components.homeconnect] Entity update triggered on <Entity Oppvaskmaskin Door: off>
2019-02-27 20:47:57 DEBUG (SyncWorker_10) [custom_components.homeconnect.switch] Updated, new state: False
2019-02-27 20:47:57 DEBUG (Thread-4) [custom_components.homeconnect] Entity update triggered on <Entity Oppvaskmaskin Remaining Program Time: None>
2019-02-27 20:47:57 DEBUG (SyncWorker_4) [custom_components.homeconnect.binary_sensor] Updated, new state: False
2019-02-27 20:47:57 DEBUG (Thread-4) [custom_components.homeconnect] Entity update triggered on <Entity Oppvaskmaskin Program Progress: None>
2019-02-27 20:47:57 DEBUG (SyncWorker_4) [custom_components.homeconnect.sensor] Updated, new state: None
2019-02-27 20:47:57 DEBUG (Thread-4) [custom_components.homeconnect] Entity update triggered on <Entity Oppvaskmaskin Program Auto1: off>
2019-02-27 20:47:57 DEBUG (Thread-4) [custom_components.homeconnect] Entity update triggered on <Entity Oppvaskmaskin Program Auto2: off>
2019-02-27 20:47:57 DEBUG (Thread-4) [custom_components.homeconnect] Entity update triggered on <Entity Oppvaskmaskin Program Auto3: off>
2019-02-27 20:47:57 DEBUG (SyncWorker_12) [custom_components.homeconnect.sensor] Updated, new state: None
2019-02-27 20:47:57 DEBUG (SyncWorker_17) [custom_components.homeconnect.switch] Updated, new state: False
2019-02-27 20:47:57 DEBUG (Thread-4) [custom_components.homeconnect] Entity update triggered on <Entity Oppvaskmaskin Program Eco50: off>
2019-02-27 20:47:57 DEBUG (Thread-4) [custom_components.homeconnect] Entity update triggered on <Entity Oppvaskmaskin Program Quick45: off>
2019-02-27 20:47:57 DEBUG (SyncWorker_0) [custom_components.homeconnect.switch] Updated, new state: False
2019-02-27 20:47:57 DEBUG (SyncWorker_13) [custom_components.homeconnect.switch] Updated, new state: False
2019-02-27 20:47:57 DEBUG (SyncWorker_2) [custom_components.homeconnect.switch] Updated, new state: False
2019-02-27 20:47:57 DEBUG (SyncWorker_1) [custom_components.homeconnect.switch] Updated, new state: False
```

**Comment by DavidMStraub** [comment]
Thanks, that was very useful! It seems that `PowerState` is not really reported by the event stream, so I just pushed a change that also uses `OperationState` to infer if the device is on or off. Hopefully now this works more reliably.

**Comment by t0bse** [comment]
your newest update is working for coffee machine! i can switch it on and the state isn't saved. but if i click "on" and a second later "off" it turns off. nice one :) thank you for your work!

**Comment by DavidMStraub** [comment]
After fixing a few things, I believe this can finally be closed! At least my oven switches on/off now flawlessly.

When still encountering issues please comment, but first have a look at the HA log: in many cases, switching on or off or both is not allowed by the API. In such a case, the switch will be unresponsive, but should still reflect the correct state.
