### ISSUE TITLE
Error during Setup - HA 0.90.3

### ISSUE THREAD

**Issue by t0bse** [DavidMStraub/homeassistant-homeconnect#18]
Homeconnect isn't starting anymore since updating to 0.90.3:

Error during setup of component homeconnect
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/homeassistant/setup.py", line 154, in _async_setup_component
    component.setup, hass, processed_config)  # type: ignore
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/homeconnect/__init__.py", line 72, in setup
    hass.data[DOMAIN]['devices'] = get_devices(hc)
  File "/config/custom_components/homeconnect/__init__.py", line 129, in get_devices
    appl = retry(hc.get_appliances, times=20, sleep=0.1)
  File "/config/custom_components/homeconnect/__init__.py", line 120, in retry
    return f()
  File "/config/deps/lib/python3.7/site-packages/homeconnect/api.py", line 146, in get_appliances
    data = self.get(ENDPOINT_APPLIANCES)
  File "/config/deps/lib/python3.7/site-packages/homeconnect/api.py", line 109, in get
    raise HomeConnectError(res['error'])
homeconnect.api.HomeConnectError: {'key': 'SDK.Error.504.GatewayTimeout', 'description': 'Timeout on Home Connect subsystem. Please try it again.'}

**Comment by override80** [comment]
I guess there might be some issues on home-connect api side - I tried deleting and reauthorizing my application but when i click "Link homeconnect account" during the configuration phase i get in response by oauth either one of the two following pages:

![Schermata 2019-04-12 alle 12 06 16](https://user-images.githubusercontent.com/43748388/56029953-ec366a00-5d1b-11e9-9e70-e3100061c2c6.png)
![Schermata 2019-04-12 alle 12 08 51](https://user-images.githubusercontent.com/43748388/56029954-ec366a00-5d1b-11e9-8921-6d22c30f2475.png)

**Comment by DavidMStraub** [comment]
I contacted support and they confirmed that the API is down, they are working on fixing it...

**Comment by anthonyangel** [comment]
The app is working, I assumed that they'd dogfood their own API's for the app
