### ISSUE TITLE
problems with initiating component

### ISSUE THREAD

**Issue by marcelwestrahome** [DavidMStraub/homeassistant-homeconnect#25]
Hi, after a few months I got this error:

Error during setup of component homeconnect:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/homeassistant/setup.py", line 156, in _async_setup_component
    component.setup, hass, processed_config)  # type: ignore
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/homeconnect/__init__.py", line 57, in setup
    simulate=config.get(DOMAIN, {}).get('simulate', False))
  File "/config/deps/lib/python3.7/site-packages/homeconnect/api.py", line 30, in __init__
    self.connect()
  File "/config/deps/lib/python3.7/site-packages/homeconnect/api.py", line 69, in connect
    token = self.token_load()
  File "/config/deps/lib/python3.7/site-packages/homeconnect/api.py", line 50, in token_load
    token = json.load(f)
  File "/usr/local/lib/python3.7/json/__init__.py", line 296, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/usr/local/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.7/json/decoder.py", line 340, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 1 column 4258 (char 4257)

**Comment by marcelwestrahome** [comment]
I have a washingmachine and oven

**Comment by DavidMStraub** [comment]
This happened to me as well and I don't understand where it's coming from; possibly a bug in the requests-oauthlib package.

A workaround is to delete the `homeconnect-token-cache.json` and restart HA.

**Comment by marcelwestrahome** [comment]
OK I will try

**Comment by marcelwestrahome** [comment]
solved, I still have another problem, the switch of the oven is always going back to off. After turning on, I have to turn it on and off very quickly to turn it off.

**Comment by DavidMStraub** [comment]
Indeed, I have the same problem and I am trying to debug it. The on/off problem is tracked in #10.
