### ISSUE TITLE
'OAuth2Session' object has no attribute 'async_refresh_token'

### ISSUE THREAD

**Issue by DavidMStraub** [DavidMStraub/homeassistant-homeconnect#43]
The specific backtrace that I get is slightly different than the one posted above:
```
Error setting up entry Configuration.yaml for homeconnect

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/homeconnect/api.py", line 65, in request
    return getattr(self._oauth, method)(url, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 546, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests_oauthlib/oauth2_session.py", line 478, in request
    url, http_method=method, body=data, headers=headers
  File "/usr/local/lib/python3.7/site-packages/oauthlib/oauth2/rfc6749/clients/base.py", line 198, in add_token
    raise TokenExpiredError()
oauthlib.oauth2.rfc6749.errors.TokenExpiredError: (token_expired) 

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 192, in async_setup
    hass, self
  File "/config/custom_components/homeconnect/__init__.py", line 82, in async_setup_entry
    await update_all_devices(hass, entry)
  File "/config/custom_components/homeconnect/__init__.py", line 114, in update_all_devices
    data[DEVICES] = await hass.async_add_executor_job(hc.get_devices)
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/homeconnect/api.py", line 45, in get_devices
    appl = self.get_appliances()
  File "/usr/local/lib/python3.7/site-packages/homeconnect/api.py", line 123, in get_appliances
    data = self.get(ENDPOINT_APPLIANCES)
  File "/usr/local/lib/python3.7/site-packages/homeconnect/api.py", line 73, in get
    res = self.request("get", endpoint)
  File "/usr/local/lib/python3.7/site-packages/homeconnect/api.py", line 67, in request
    self._oauth.token = self.refresh_tokens()
  File "/config/custom_components/homeconnect/api.py", line 39, in refresh_tokens
    self.session.async_ensure_token_valid(), self.hass.loop
  File "/usr/local/lib/python3.7/concurrent/futures/_base.py", line 435, in result
    return self.__get_result()
  File "/usr/local/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/usr/src/homeassistant/homeassistant/helpers/config_entry_oauth2_flow.py", line 403, in async_ensure_token_valid
    new_token = await self.implementation.async_refresh_token(self.token)
AttributeError: 'OAuth2Session' object has no attribute 'async_refresh_token'
```

I installed home-connect via HACS and then added it via "Integrations", yes. I still have the
```yaml
homeconnect:
  client_id: !secret homeconnect_id
  client_secret: !secret homeconnect_secret
```
entry in my `configuration.yaml`, though.

I previously had the custom component manually installed without HACS, but I completely removed the folder in `/config/custom_components/` before reinstalling via HACS.

_Originally posted by @sharkdp in https://github.com/DavidMStraub/homeassistant-homeconnect/issues/17#issuecomment-557832805_

**Comment by DavidMStraub** [comment]
@sharkdp I believe I identified and fixed the bug, can you please try it out? (E.g. by installing from master in HACS.)

**Comment by sharkdp** [comment]
Thank you for looking into this!

I installed `master` and it does work just fine. However, note that I previously got rid of the error removing/adding the integration in HA. So I cannot really make any statements about whether or not it fixes the error.

**Comment by DavidMStraub** [comment]
Right. The tokens have a lifetime of 24 hours, so the error doesn't show up before that.

**Comment by sharkdp** [comment]
It's been over 48 hours now and I'm still connected.

It looks to me like your fix worked :+1:

**Comment by DavidMStraub** [comment]
For me as well, thanks for testing!
