### ISSUE TITLE
No module named "homeconnect"

### ISSUE THREAD

**Issue by leaskovski** [DavidMStraub/homeassistant-homeconnect#51]
Not sure if I am doing something totally stupid or not, but I have followed the installation details, created my app on the home connect website, then copied the custom component to my hass config custom components folder, and added the config settings as described.

When restarting hass, my log contains...

```
2020-01-10 17:19:37 ERROR (MainThread) [homeassistant.loader] Error loading custom_components.homeconnect. Make sure all dependencies are installed
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.6/site-packages/homeassistant/loader.py", line 346, in _load_file
    module = importlib.import_module(path)
  File "/usr/local/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/media/USBHDD1/homeassistant/custom_components/homeconnect/__init__.py", line 21, in <module>
    from . import api, config_flow
  File "/media/USBHDD1/homeassistant/custom_components/homeconnect/api.py", line 6, in <module>
    import homeconnect
ModuleNotFoundError: No module named 'homeconnect'
2020-01-10 17:19:37 ERROR (MainThread) [homeassistant.components.homeassistant] Component error: homeconnect - Integration 'homeconnect' not found.
```

This a python version issue, or something else?  I am running 0.102.1.  I have one other custom component, heatmiserneo.

Thanks

**Comment by DavidMStraub** [comment]
That's very surprising. Normally, Home Assistant automatically installs the required modules. I don't understand why this doesn't happen here. That makes it hard to debug. Does the problem persist when you restart HA? When you remove the integration and add it again?

**Comment by qwt2003** [comment]
@DavidMStraub I think you lost a step after copy the homeconnects to the custom_components. After you upload the files, you should REBOOT your homeassistant or HASSIO, NOT THE SERVICE!

**Comment by DavidMStraub** [comment]
True. If you have time to add it yourself that would be great.

**Comment by leaskovski** [comment]
Not sure what the issue here was, but I took the time to upgrade my python install the 3.7 and thus create a new python env to run hass in.  Now I have done that, it all seems to be starting up ok.  So I am going to close this off.
