### ISSUE TITLE
Error loading custom_components.homeconnect.

### ISSUE THREAD

**Issue by ronniebach** [DavidMStraub/homeassistant-homeconnect#55]
I've followed the instruction. Copied the folder homeconnect into /custom-components
Added homeconnect: to configuration.yaml

Receives this error:

2020-01-26 14:56:52 ERROR (MainThread) [homeassistant.loader] Error loading custom_components.homeconnect. Make sure all dependencies are installed
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 379, in _load_file
    module = importlib.import_module(path)
  File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/config/custom_components/homeconnect/__init__.py", line 21, in <module>
    from . import api, config_flow
  File "/config/custom_components/homeconnect/api.py", line 6, in <module>
    import homeconnect
ModuleNotFoundError: No module named 'homeconnect'
2020-01-26 14:56:57 ERROR (MainThread) [homeassistant.components.hassio] Component error: homeconnect - Integration 'homeconnect' not found.

**Comment by DavidMStraub** [comment]
Did you restart Home Assistant?

**Comment by ronniebach** [comment]
yes, the error appeared in the log during restart of Home Assistant.

**Comment by DavidMStraub** [comment]
It's surprising as HA is supposed to install all dependencies from `manifest.json` during setup of the component and this always worked for me so far. Are you using Hassio?

I wonder if this is related to #13.

**Comment by ronniebach** [comment]
Yes, using HAssio..
And I copied the folder homeconnect into /custom-components
Then in UI clicks on Configurator > Settings > Restart HASS

Should that be sufficient?

**Comment by DavidMStraub** [comment]
I think so. No idea what is happening there. Does someone else encounter this?

**Comment by ronniebach** [comment]
Well it was in fact not enough to only restart HASS. Had to reboot - then it correctly installed all dependencies. Works perfect now :-) Thanks.
